config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  resources :users, only: %i[new create show edit update]
  resources :events, only: %i[new create show index]
  get '/welcome', to: 'sessions#welcome'
  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'
  post '/attend', to: 'event_attendings#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :event_attendings
  has_many :event_attendees, through: 'event_attendings', source: :user

  scope :upcoming_events, -> { where('date >= ?', Date.today).order('date DESC') }
  scope :previous_events, -> { where('date < ?', Date.today).order('date DESC') }

  validates :name, :description, :date, :location,
            presence: true

  def past?
    date < Date.today
  end
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :event_attendings
  has_many :attended_events, through: 'event_attendings', source: :event

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :signed_in?
  helper_method :new_event

  def current_user
    User.find_by(id: session[:user_id])
  end

  def signed_in?
    current_user
  end

  def new_event
    if signed_in?
      redirect_to new_event_path
    else
      redirect_to root_path, alert: 'You must login first'
    end
  end
end

app/controllers/event_attendings_controller.rb
class EventAttendingsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    if @event.event_attendees.include? current_user
      redirect_to event_path(@event), alert: 'You are already attendee'
    else
      @event.event_attendees << current_user
      redirect_to event_path(@event), notice: 'Attendance confirmed'
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @user = User.find(current_user.id)
    @event = @user.created_events.build(event_params)
    redirect_to root_path, notice: 'Event successfully created' if @event.save

    render 'new' unless @event.save
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @upcoming_events = Event.upcoming_events
    @previous_events = Event.previous_events
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date, :location)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(name: params[:name])
    if @user
      session[:user_id] = @user.id

      redirect_to root_url, notice: 'Successfully signed in, cheers!'
    else
      redirect_to root_path, alert: 'Oops! cannot sign in, check and try again or sign up'
    end
  end

  def destroy
    session.destroy

    redirect_to root_url, notice: 'Successfully signed out!'
  end

  def welcome
    @upcoming_events = Event.upcoming_events
    @previous_events = Event.previous_events
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: 'You have signed up succesfully, please sign in'
    else
      render 'new', alert: 'Sign up failed, Please check and try again'
    end
  end

  def show
    @user = current_user
    @created_events = @user.created_events
    @previously_attended_events = current_user.attended_events.previous_events
    @to_attend_events = current_user.attended_events.upcoming_events
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)

      redirect_to user_path(@user), notice: 'Details updated successfully'
    else
      render 'edit', alert: 'Cannot update, check your entry'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendings_helper.rb
module EventAttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attend.html.erb
<% unless @event.past? %>
  <%= form_with(url: '/attend', local: true) do |f| %>
    <%= f.hidden_field :event_id, class: :form_control, value: @event.id %>
    <div class="actions text-center">
      <%= f.submit 'Confirm Attendance', class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/events/_badge.html.erb
<% if @event.past? %>
  <span class="badge badge-pill badge-danger">Ended</span>
<% else %>
  <span class="badge badge-pill badge-success">Upcoming</span>
<% end %>

app/views/events/index.html.erb
<div class="card w-75 mx-auto px-3">
  <div class="card-header text-center mb-2">
    <h1>All Events</h1>
   </div> 

  <h3>Upcoming Events</h3>
  <ul class="list-unstyled">
    <% @upcoming_events.each do |event| %>
      <li>+ <%= link_to event.name, event_path(event) %></li>
    <% end %>
  </ul>
  <h3>Previous Events</h3>
  <ul class="list-unstyled">
    <% @previous_events.each do |event| %>
      <li>+ <%= link_to event.name, event_path(event) %></li>
    <% end %>
  </ul>
  <%= link_to "Home", root_path, class: "pb-3" %>
</div>

app/views/events/new.html.erb
<div class="card w-50 mx-auto mt-2">
  <div class="card-header">
    <h1 class="text-center">Create an Event</h1>
   </div> 

  <div class="card-body">
    <%= form_with(model: @event, local: true) do |f| %>
      <div class="form-group">
        <%= f.label "name:" %>
        <%= f.text_field :name, autofocus: true, placeholder: "What to call your event", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label "description:" %>
        <%= f.text_area :description, placeholder: "Event details here...", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label "date:" %>
        <%= f.date_field :date, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label "location:" %>
        <%= f.text_field :location, placeholder: "Enter location", class: "form-control" %>
      </div>

      <div class="actions mb-3">
        <%= f.submit %>
      </div>
    <% end %>
    <%= link_to "Cancel", root_path %>
  </div>
</div>

app/views/events/show.html.erb
<div class="card w-50 mx-auto">
  <p class="p-3 mb-0">
    <strong>Created By:</strong> <%= @event.creator.name %>
    on <%= @event.created_at.strftime('%a, %d-%b-%Y') %>
  </p>
  <div class="card-header text-white bg-dark d-flex justify-content-between">
    <h2>Event:- <%= @event.name %><%= render 'events/badge' %></h2>   
  </div>
  <div class="card-body">
    <h4 class="mb-2">Event Description: </h4><%= @event.description %>
    <p class="mt-3"><strong>Happening On: </strong><%= @event.date.strftime('%a, %d-%b-%Y') %></p>
    <p><strong>Location: </strong><%= @event.location%></p>

    <h4><%= pluralize(@event.event_attendees.count, "Attendee") %></h4>
    <ul class="list-unstyled">
      <% @event.event_attendees.each do |attendee| %>
        <% if attendee == current_user %>
          <li>+ <%= link_to current_user.name, user_path(current_user) %></li>
        <% else %>
          <li>+ <%= attendee.name %></li>
        <% end %>  
      <% end %>
    </ul>
    <%= render 'events/attend' %>
    <%= link_to 'Home', root_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="text-center">
        <span class="alert alert-success"><%= notice%></span>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="text-center">
        <span class="alert alert-danger"><%= alert %></span>
      </div>
    <% end %>
    <%= render 'users/nav' %>
    <%= yield %>
  </body>
</html>

app/views/users/_events.html.erb
<ul class="list-unstyled">
  <% @created_events.each do |event| %>
    <li>+ <%= link_to event.name, event_path(event) %></li>
  <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_for(@user, local: true) do |f| %>
  <div class="form-group">
    <%= f.label "name:" %>
    <%= f.text_field :name, required: true, autofocus: true, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Sign Up' %>
  </div>
<% end %>

app/views/users/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-info sticky-top">
  <div class="container-fluid">
    <%= link_to "Private Events", root_path, class: "navbar-brand" %>
    <ul class="navbar-nav">
      <li class="navbar-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if signed_in? %>
        <li class="navbar-item">
          <%= link_to "Created Events", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="navbar-item">
          <%= link_to "All Events", root_path, class: "nav-link", value: "All Events" %>
        </li>
        <li class="navbar-item">
            <%= link_to "New Event", new_event_path, class: "btn btn-light" %>
        </li>
      <% end %>
    </ul>

    <div class="navbar-right ml-auto">
      <% if signed_in? %>
        <span class="text_secondary">Signed in as: </span>
        <%= link_to current_user.name, user_path(current_user), class: "btn btn-outline-light" %>
        <%= link_to "Sign Out", sign_out_path, method: :delete, class: "btn btn-danger"%>
      <% end %>
    </div>
  </div>
</nav>

app/views/users/edit.html.erb
<div class="card w-25 mx-auto mt-2">
  <div class="card-header">
    <h1>Edit Profile</h1>
  </div>
  <div class="card-body">
    <%= render 'users/form' %>
  </div>
  <%= link_to "Cancel", user_path(@user), class: "pl-3" %>
</div>

app/views/users/new.html.erb
<div class="card w-25 mx-auto mt-3">
  <div class="card-header">
    <h1>Sign Up</h1>
  </div> 

  <div class="card-body">
    <%= render 'users/form' %>
  </div>
  <%= link_to "Cancel", root_url, class: "pl-3" %>
</div>

app/views/users/show.html.erb
<div class="card w-50 mx-auto">
  <div class="card-header text-white bg-warning">
    <h1><%= @user.name %> 's Profile</h1>
    <%= link_to "Edit profile", edit_user_path(@user) %>
  </div>
  <div class="card-body">
    <h3><%= pluralize(@user.created_events.count, "event") %> created</h3>
    <%= render 'users/events' %>
    <h3><%= pluralize(@user.attended_events.count, "Event") %> as Attendee</h3>
    <div class="previous">
      <h5>Previously Attended Events</h5>
      <ul class="list-unstyled">
        <% @previously_attended_events.each do |event| %>
          <li>+ <%= link_to event.name, event_path(event) %></li>
        <% end %>
      </ul>
    </div>
    <div class="to_attend">
      <h5>Events to Attend</h5>
      <ul class="list-unstyled">
        <% @to_attend_events.each do |event| %>
          <li>+ <%= link_to event.name, event_path(event) %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <%= link_to "Home", root_url, class: "pl-3" %>
</div>